In [6]:
import numpy
n = numpy.arange(12)
n
type(n)

numpy.ndarray

In [18]:
import cv2

im_g = cv2.imread('assets/smallgray.png', 1)
print(im_g)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [19]:
im_g = cv2.imread('assets/smallgray.png', 0)
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
